// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBh58GRmGJGxVt5DzCeQ1Q1syUEVMlZPoQ',
    appId: '1:571029752481:web:3d79e037749acee39efee0',
    messagingSenderId: '571029752481',
    projectId: 'it-shop-fe504',
    authDomain: 'it-shop-fe504.firebaseapp.com',
    storageBucket: 'it-shop-fe504.appspot.com',
    measurementId: 'G-YDZ78ZS6EQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGK59oDw5MuA_I7Ug-4Zu1tQAXpllg_kc',
    appId: '1:571029752481:android:798b228cf12854479efee0',
    messagingSenderId: '571029752481',
    projectId: 'it-shop-fe504',
    storageBucket: 'it-shop-fe504.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMfRHmd1xh9xtdVCu5b3lIpHei58U7bAE',
    appId: '1:571029752481:ios:9cc652e9d1d232b49efee0',
    messagingSenderId: '571029752481',
    projectId: 'it-shop-fe504',
    storageBucket: 'it-shop-fe504.appspot.com',
    androidClientId: '571029752481-8u7rhoe9789a2bdlb8gnt9jbhechfinr.apps.googleusercontent.com',
    iosClientId: '571029752481-t9nd9hudqjm82rgkeivflaufq7qobqg6.apps.googleusercontent.com',
    iosBundleId: 'com.itshop.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMfRHmd1xh9xtdVCu5b3lIpHei58U7bAE',
    appId: '1:571029752481:ios:06e767393e9a2a139efee0',
    messagingSenderId: '571029752481',
    projectId: 'it-shop-fe504',
    storageBucket: 'it-shop-fe504.appspot.com',
    androidClientId: '571029752481-8u7rhoe9789a2bdlb8gnt9jbhechfinr.apps.googleusercontent.com',
    iosClientId: '571029752481-tb4ch91u4pgrjdmfltp41bci371602mv.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseEcommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBh58GRmGJGxVt5DzCeQ1Q1syUEVMlZPoQ',
    appId: '1:571029752481:web:034516207cd9784e9efee0',
    messagingSenderId: '571029752481',
    projectId: 'it-shop-fe504',
    authDomain: 'it-shop-fe504.firebaseapp.com',
    storageBucket: 'it-shop-fe504.appspot.com',
    measurementId: 'G-W33KJZ34TK',
  );

}